#!/bin/sh
# USAGE: jevois-build.sh [destdir|jevois-flash-card args]
#
# This script compiles the platform operating system and all its packages, then installs the resulting bootloaders and
# root filesystem to /var/lib/jevois-build (or destdir, if specified), and finally runs jevois-flash-card (unless
# destdir was specified) to flash a microSD card.

destdir=$1
if [ "X${destdir}" = "X" ]; then destdir="/var/lib/jevois-build"; fi

./build.sh && ./build.sh pack

if [ $? -ne 0 ]; then exit 1; fi

tmp=`mktemp -dp .`

# caution: this is generated by build.sh pack:
cp tools/pack/chips/sun8iw5p1/bin/boot0_sdcard_sun8iw5p1.bin ${tmp}/boot0_sdcard.fex
cp tools/pack/out/sys_config.bin ${tmp}/sys_config.bin
./tools/pack/pctools/linux/mod_update/update_boot0 ${tmp}/boot0_sdcard.fex ${tmp}/sys_config.bin SDMMC_CARD
cp tools/pack/chips/sun8iw5p1/bin/u-boot-sun8iw5p1.bin ${tmp}/u-boot.fex
./tools/pack/pctools/linux/mod_update/update_uboot ${tmp}/u-boot.fex ${tmp}/sys_config.bin 

sudo mkdir -p ${destdir}
sudo cp ${tmp}/u-boot.fex ${tmp}/boot0_sdcard.fex ${destdir}/
sudo cp ${tmp}/sys_config.bin ${destdir}/script.bin
sudo cp linux-3.4/arch/arm/boot/uImage ${destdir}/
sudo cp out/sun8iw5p1/linux/common/rootfs.ext4 ${destdir}/
sudo cp jevois-build/microsd-readme.txt ${destdir}/
sudo cp jevois-build/uEnv.txt ${destdir}/

/bin/rm -rf "${tmp}"

# proceed with flashing an SD unless a custom destination was chosen, in which case probably this script is used as a
# step in a broader build process:
if [ "X${destdir}" = "X/var/lib/jevois-build" ]; then
    cd jevois-build && sudo ./jevois-flash-card $*
fi

