#!/bin/sh

./build.sh # && ./build.sh pack

if [ $? -ne 0 ]; then exit 1; fi

tmp=`mktemp -dp .`

# caution: this is generated by build.sh pack:
cp tools/pack/chips/sun8iw5p1/bin/boot0_sdcard_sun8iw5p1.bin ${tmp}/boot0_sdcard.fex
cp tools/pack/out/sys_config.bin ${tmp}/sys_config.bin
./tools/pack/pctools/linux/mod_update/update_boot0 ${tmp}/boot0_sdcard.fex ${tmp}/sys_config.bin SDMMC_CARD
cp tools/pack/chips/sun8iw5p1/bin/u-boot-sun8iw5p1.bin ${tmp}/u-boot.fex
./tools/pack/pctools/linux/mod_update/update_uboot ${tmp}/u-boot.fex ${tmp}/sys_config.bin 

cp ${tmp}/u-boot.fex ${tmp}/boot0_sdcard.fex jevois-build/
cp ${tmp}/sys_config.bin jevois-build/script.bin
cp linux-3.4/arch/arm/boot/uImage jevois-build/
cp out/sun8iw5p1/linux/common/rootfs.ext4 jevois-build/

/bin/rm -rf "${tmp}"

cd jevois-build && sudo ./jevois-flash-card.sh $*

