# This file is mainly for JeVois development team
#
# Most users would just: (replace VERSION by a version number, e.g., 1.23.0)
#   docker pull jevois/jevois-compile-modules:VERSION
#   cd jevois-sdk
#   ./docker/compile-modules-in-docker.sh
#
# JeVois team: To create the docker image:
#
# Install docker as described here (we chose the apt-based install for Ubuntu):
# https://docs.docker.com/engine/install/ubuntu/
#
# Then build with: docker build -t jevois/jevois-compile-modules:VERSION -f Dockerfile-compile-modules .
# Then push to docker hub: docker login && docker image push jevois/jevois-compile-modules:VERSION

FROM ubuntu:24.04

# Update package sources:
RUN apt-get update && apt-get -y upgrade && apt-get -y dist-upgrade

# Install packages needed to add a deb source and generate a locale:
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install ca-certificates gpg locales sudo

# Install jevois.usc.edu apt repo:
RUN gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys DD24C027 && \
    gpg --export DD24C027 > /etc/apt/trusted.gpg.d/jevois.gpg
RUN echo "deb https://jevois.usc.edu/apt noble main" > /etc/apt/sources.list.d/jevois.list
    
# Update package sources:
RUN apt-get update && apt-get -y upgrade && apt-get -y dist-upgrade

# Install everything:
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install jevois-sdk-dev

# Set g++-10 as default:
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 --slave /usr/bin/g++ g++ /usr/bin/g++-10 \
  --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-10 && update-alternatives --set gcc /usr/bin/gcc-10
RUN update-alternatives --set gcc /usr/bin/gcc-10

# Clean up:
RUN apt-get -y autoremove

# Generate a US locale:
RUN locale-gen en_US.UTF-8
ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en' LC_ALL='en_US.UTF-8' TERM=screen

# Get ready to run as the same user as the caller:
COPY with_the_same_user /
